#!/usr/bin/env python3
"""correctness_goldens.json batch — judge-reference rows, 107 rows (100-120 band).
Same 8-key schema + T-01 suite as retriever/routing. id numbering continues the per-source
seq (S1-Q046+, ...). Cross-file asserts: no id/query collisions with the two existing files.
"""
import json, re

from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]  # this file lives at <repo>/tools/goldens/

DATA = str(ROOT / "data" / "docs") + "/"
GOLD = str(ROOT / "eval" / "goldens" / "correctness_goldens.json")
SRC = {
    "S1": "s1_early_steps_bundle.md", "S2": "s2_frameworks_bundle.md",
    "S3": "s3_lifecycle_bundle.md", "S4": "s4_qa_deep_dives.md", "S5": "s5_docs_bundle.md",
}
bund = {k: open(DATA + v, encoding="utf-8").read() for k, v in SRC.items()}
lines = {k: v.splitlines(keepends=True) for k, v in bund.items()}

def A(src, nums, marker):
    txt = "".join(lines[src][i - 1] for i in nums).rstrip("\n")
    assert marker in txt, f"MARKER FAIL {src} {nums}: {marker!r} -> {txt[:80]!r}"
    assert txt in bund[src], f"NOT CONTIGUOUS {src} {nums}"
    return txt

def expect_path(srcs):
    return " + ".join("data/docs/" + SRC[s] for s in srcs)

def R(i, cat, q, ans, src, nums, marker, must, ctxsrc=None):
    cs = ctxsrc or src
    return {
        "id": i, "category": cat, "query": q, "ideal_answer": ans,
        "ideal_context": A(cs, nums, marker),
        "must_contain": must, "source": src, "path": expect_path(src.split("+")),
    }

NEW = []

# ---------------- S1 correctness (Q046..Q066) ----------------
S1 = "S1"
NEW += [
R("S1-Q046", "cite",
  "Why does step 1 avoid an external vector database for retrieval?",
  "Step 1's vector store is pure numpy — no Qdrant, no Chroma, no external DB — an in-memory store over numpy arrays. It is the simplest possible design with no server, so the later framework choices are changes, not requirements.",
  S1, [173], "Pure numpy",
  ["Pure numpy", "no Qdrant, no Chroma"]),
R("S1-Q047", "cite",
  "Why does the step-1 chunker overlap its windows?",
  "Fixed-size chunking runs at chunk_size 512 tokens with chunk_overlap 50 tokens; the overlap prevents information loss at chunk boundaries, balancing context richness against retrieval precision.",
  S1, [127, 128], "512 tokens",
  ["512 tokens", "50 tokens"]),
R("S1-Q048", "cite",
  "What is the exact refusal the step-1 generator emits when the context lacks the answer?",
  "The generator answers based ONLY on the provided context; if the context doesn't contain the answer, it says 'I don't have enough information to answer this question.'",
  S1, [262, 263, 264], "I don't have enough information",
  ["based ONLY on the", "I don't have enough information to answer this question."]),
R("S1-Q049", "cite",
  "What is the reasoning behind the step-1 generator's temperature?",
  "max_tokens 1024 leaves room for the context in the prompt; temperature 0.1 keeps creativity low for factual answers; top_p 0.9 focuses on the most probable tokens.",
  S1, [287, 288, 289], "1024",
  ["1024", "0.1", "0.9"]),
R("S1-Q050", "cite",
  "What does the step-2 evaluator's 'Context Recall ≥ 0.7' target actually require?",
  "The target is ≥ 0.7: 70% of the gold answer's key points should be covered by the retrieved chunks.",
  S1, [982], "**Target:** ≥ 0.7",
  ["**Target:** ≥ 0.7", "gold answer points"]),
R("S1-Q051", "cite",
  "Why was gpt-oss-120b chosen as the eval judge?",
  "openai/gpt-oss-120b is the only freely-accessible model verified on the Groq account, so the step-2 DeepEval suite uses it as the judge.",
  S1, [1208], "openai/gpt-oss-120b",
  ["openai/gpt-oss-120b", "only freely-accessible model verified"]),
R("S1-Q052", "cite",
  "How many easy, medium, and hard questions does the step-2 golden set aim for?",
  "20–30 Q&A pairs: 10 easy (direct fact lookup), 10 medium (requires understanding), and 5–10 hard (multi-hop reasoning, cross-document).",
  S1, [1163, 1164, 1165, 1166], "20-30 pairs",
  ["10 easy", "10 medium", "5-10 hard"]),
R("S1-Q053", "cite",
  "What do the trace timings show about chunking and embedding at step 2?",
  "The LangSmith trace example shows the chunker turning 4 files into 60 chunks (0.12s), then embedding 1 query into a 1024-dim vector.",
  S1, [1091, 1092, 1093, 1094], "4 files → 60 chunks",
  ["4 files → 60 chunks", "1024-dim vector"]),
R("S1-Q054", "cite",
  "Can an approved prompt version be promoted again or edited?",
  "No: the lifecycle is DRAFT → TESTING → APPROVED → RETIRED, forward only; a retired prompt is terminal (cannot be promoted) and approved templates are immutable.",
  S1, [411], "DRAFT → TESTING",
  ["DRAFT → TESTING → APPROVED → RETIRED", "forward only"]),
R("S1-Q055", "cite",
  "Which local embedder does step 1 use, and why no API?",
  "Step 1 converts text chunks into dense vector representations — 768-dimensional vectors via BAAI/bge-base-en-v1.5, run locally through fastembed (local ONNX, no API needed).",
  S1, [144, 145], "768-dimensional",
  ["768-dimensional", "dense vector representations"]),
R("S1-Q056", "degrade",
  "What does the step-2 judge wrapper do when Groq returns HTTP 429?",
  "429s are retried up to 10x, sleeping the exact retry-after seconds parsed from the error message, so rate-limit responses don't fail the eval run.",
  S1, [1208], "429s are retried",
  ["429s are retried"]),
R("S1-Q057", "degrade",
  "What shared mechanism limits concurrent judge calls on the Groq free tier, and what is its default?",
  "Judge calls are serialized through a shared async semaphore — JUDGE_MAX_CONCURRENT, default 1 — because the free tier is TPM-limited to about 8000 tokens/min.",
  S1, [1208], "JUDGE_MAX_CONCURRENT",
  ["8000 tokens/min", "JUDGE_MAX_CONCURRENT"]),
R("S1-Q058", "abstain",
  "What does the step-1 stack cost per month in dollars?",
  "Not derivable from the corpus: step 1's cost table records each component as free (embeddings local, vector store local, LLM 30 RPM free tier) but no monthly dollar figure is given — do not invent a budget.",
  S1, [635, 636, 637], "Free (local)",
  ["Free (local)", "Free (30 RPM)"]),
R("S1-Q059", "cite",
  "What does step 1's component cost table list for embeddings, the vector store, and the LLM?",
  "Embeddings: fastembed bge-base-en-v1.5, free (local), 768-dim CPU, no API. Vector store: numpy cosine similarity, free (local), no server. LLM: Groq llama-3.3-70b-versatile, free (30 RPM), 200–350 tok/s 70B quality.",
  S1, [635, 636, 637], "llama-3.3-70b-versatile",
  ["bge-base-en-v1.5", "numpy cosine similarity", "llama-3.3-70b-versatile", "30 RPM"]),
R("S1-Q060", "cite",
  "What steps happen inside step 1's ask(question, top_k=3) flow?",
  "ask(question, top_k=3) embeds the question, retrieves the top-k chunks, generates an answer with that context, and returns the answer plus citations.",
  S1, [310, 311, 312, 313, 314], "ask(question, top_k=3)",
  ["ask(question, top_k=3)", "retrieve top-k chunks", "return answer + citations"]),
R("S1-Q061", "cite",
  "How many LangSmith traces are free per month, and is that enough?",
  "LangSmith offers 5,000 traces/month free — 'More than enough for learning.'",
  S1, [1134], "5,000 traces/month free",
  ["5,000 traces/month free"]),
R("S1-Q062", "cite",
  "What does each step-2 chat-log entry record, and where do the logs live?",
  "Every user/assistant exchange appends to data/chat_logs/chat_log_<YYYY_MM_DD>.jsonl — JSONL objects with timestamp, user_message, agent_message, prompt_key, config, and num_sources; durable, local, gitignored, and independent of LangSmith.",
  S1, [1486], "chat_log_<YYYY_MM_DD>",
  ["timestamp, user_message, agent_message", "prompt_key", "num_sources"]),
R("S1-Q063", "misroute",
  "Which vector database powers step 1's retrieval?",
  "None — step 1's vector store is pure numpy, with no Qdrant, no Chroma, and no external DB. A router keying on 'vector DB' or 'Faiss' must not land on the step-4 deep dive or the framework bundle for this question.",
  S1, [173], "Pure numpy",
  ["Pure numpy", "no Qdrant, no Chroma"]),
R("S1-Q064", "misroute",
  "How many free-tier requests per minute does Groq allow for the step-1 generation model?",
  "30 RPM — recorded in the step-1 cost table for llama-3.3-70b-versatile. A router keying on 'rate limit' should not jump to step-7's rate-limiting guardrail: the 30 RPM figure is the step-1 free tier.",
  S1, [637], "Free (30 RPM)",
  ["Free (30 RPM)", "llama-3.3-70b-versatile"]),
R("S1-Q065", "conflict",
  "Where do the 768-dim and 1024-dim figures in the early steps come from?",
  "Both appear, and the answer must attribute each: step 1's bge-base-en-v1.5 embeddings are 768-dimensional, while the step-2 trace example shows '1 query → 1024-dim vector' and the step-2/3 stack names qwen3-embed. Surface both sides; never merge them.",
  S1, [1097], "1024-dim vector",
  ["1024-dim vector", "768-dim"]),
R("S1-Q066", "abstain",
  "Does the corpus record any measured latency for the step-1 pipeline?",
  "No: only example run-log fields exist (latency_ms 1200 appears in a sample entry); no measured or expected production latency for the step-1 pipeline is recorded — do not invent one.",
  S1, [514, 515], "latency_ms",
  ["latency_ms"]),
]

# ---------------- S2 correctness (Q038..Q057) ----------------
S2 = "S2"
NEW += [
R("S2-Q038", "cite",
  "Why are score changes attributable when comparing step 2 and step 3?",
  "Step 3's north star is same data, same model, same metrics as step 2 — the only difference is the framework, so score changes are attributable.",
  S2, [37, 38], "score changes are attributable",
  ["same data, same model, same metrics", "score changes are attributable"]),
R("S2-Q039", "cite",
  "What is the second retrieval stage in the step-3 pipeline?",
  "A cross-encoder 2nd stage, ms-marco-MiniLM-L-6-v2, re-sorts candidates to top_n after retrieval.",
  S2, [57, 58], "ms-marco-MiniLM-L-6-v2",
  ["cross-encoder 2nd stage", "ms-marco-MiniLM-L-6-v2", "re-sort → top_n"]),
R("S2-Q040", "cite",
  "Which retrieval techniques does step 3 explicitly defer to step 4?",
  "Hybrid dense+sparse (BM25), RRF fusion, and multi-source routing are out of scope for step 3 and deferred to step 4.",
  S2, [35, 36], "RRF fusion",
  ["hybrid dense+sparse (BM25)", "RRF fusion", "multi-source"]),
R("S2-Q041", "cite",
  "Why does the retriever read Chroma's private query API?",
  "The public similarity_search hides scores, so scores are recovered via Chroma's internal _collection.query as 1−distance, keeping the step-2 {text, metadata, score} shape.",
  S2, [52], "_collection.query",
  ["_collection.query", "1−distance"]),
R("S2-Q042", "cite",
  "What does the supervisor agent do with a question in step 6?",
  "The supervisor agent analyzes the question and decides which agents to use — researcher, fact-checker, summarizer.",
  S2, [542, 543, 544], "SUPERVISOR AGENT",
  ["SUPERVISOR AGENT", "decides which agents to use"]),
R("S2-Q043", "cite",
  "What are the exact grade thresholds in the step-5 graph?",
  "score ≥ 0.7 → pass; score ≥ 0.4 → soft retry (rewrite); score < 0.4 → hard retry (re-retrieve).",
  S2, [282, 283, 284, 285, 286, 287, 288], "score ≥ 0.4",
  ["score ≥ 0.7", "score ≥ 0.4", "score < 0.4"]),
R("S2-Q044", "cite",
  "Which fields does the step-5 RAGState carry?",
  "RAGState is a TypedDict with question, context, answer, grade, and retry_count.",
  S2, [333, 334, 335, 336, 337, 338], "retry_count",
  ["RAGState", "question", "context", "grade", "retry_count"]),
R("S2-Q045", "cite",
  "What are the inputs and outputs of the step-6 fact-checker?",
  "The fact-checker validates claims in chunks — inputs are the context and the answer draft; the output is validated claims, which the summarizer turns into the final cited answer.",
  S2, [619, 620], "Validate claims in chunks",
  ["Validate claims in chunks", "Validated claims", "Cited answer"]),
R("S2-Q046", "cite",
  "How does get_for_node() find the right prompt?",
  "Prompts are keyed by the composite prompt_id + node_name + source_type, so each graph node gets its own versioned prompt looked up via get_for_node().",
  S2, [400], "prompt_id + node_name + source_type",
  ["prompt_id + node_name + source_type"]),
R("S2-Q047", "cite",
  "What comparability rule did step 3's embedder decision record?",
  "The decision record says 'Same embedding as Step 2 (qwen3-embed, 1024-dim) — Apples-to-apples A/B': keeping the embedder makes comparisons fair and score changes attributable.",
  S2, [87], "Apples-to-apples A/B",
  ["Apples-to-apples A/B", "qwen3-embed, 1024-dim"]),
R("S2-Q048", "cite",
  "Which dimensions does the shared registry treat as key rather than as new code?",
  "node_name and source_type are key dimensions, not new code — get_for_node() filters the shared store, and the class and lifecycle stay the same across steps.",
  S2, [466, 467], "key dimensions, not new code",
  ["node_name", "source_type", "key dimensions, not new code"]),
R("S2-Q049", "cite",
  "What does it mean that approved registry versions are immutable?",
  "Approved versions are immutable — a better grade-node prompt supersedes its version; you never edit in place.",
  S2, [466, 467, 468, 469], "Approved versions immutable",
  ["Approved versions immutable", "never edit in place"]),
R("S2-Q050", "cite",
  "What scorecard does the per-node eval gate record as evidence?",
  "The scorecard records per-node scores — rewrite 0.85, grade 0.72, generate 0.88 — as Evidence in the registry; only an approved node prompt is used at run time.",
  S2, [467], "rewrite 0.85",
  ["rewrite 0.85", "grade 0.72", "generate 0.88"]),
R("S2-Q051", "cite",
  "What does the step-6 LangSmith section ask about agent metrics?",
  "Its exam question asks what metrics LangSmith captures for each agent and how you use them to optimize.",
  S2, [664], "What metrics does LangSmith capture for each agent",
  ["What metrics does LangSmith capture for each agent"]),
R("S2-Q052", "cite",
  "Why is tracing essential in step 6?",
  "Without tracing you can't tell which agent is failing — the docs call LangSmith essential for debugging the agent team.",
  S2, [827], "Without tracing",
  ["Without tracing"]),
R("S2-Q053", "misroute",
  "Where does the corpus document how the step-3 retriever keeps the {text, metadata, score} shape?",
  "In the framework bundle: scores are recovered through Chroma's internal _collection.query as 1−distance because similarity_search hides them. A router keying on 'Chroma' or 'vector store' could wrongly land on the step-4 deep dive instead.",
  S2, [52], "_collection.query",
  ["_collection.query", "1−distance"]),
R("S2-Q054", "abstain",
  "What is the average number of retries the step-5 graph performs in production?",
  "Not recorded: the corpus specifies only the hard cap (give up after 3 retries); no observed or expected average retry count is documented — do not invent one.",
  S2, [383, 384, 385, 386, 387, 388, 389], "Give up after 3 retries",
  ["retry_count", "Give up after 3 retries"]),
R("S2-Q055", "abstain",
  "How much does step 6's LangSmith tracing cost per month?",
  "Not recorded in the framework bundle: the LangSmith tracing section documents observability and debugging value, but no paid pricing appears anywhere in the corpus — only the free 5,000 traces/month note exists.",
  S2, [648], "LangSmith Tracing",
  ["LangSmith Tracing"]),
R("S2-Q056", "degrade",
  "How does the step-5 graph behave when the grade keeps returning 'retry'?",
  "grade_decision keeps returning 'retry' while retry_count < 3, then gives up and returns 'pass' after 3 retries — a hard cap so a bad retrieval can't loop forever.",
  S2, [383, 384, 385, 386, 387, 388, 389], "Give up after 3 retries",
  ["retry_count", "Give up after 3 retries"]),
R("S2-Q057", "degrade",
  "A retrieval keeps grading below 0.4. What does the step-5 graph do next?",
  "score < 0.4 means a hard retry (re-retrieve); a score of 0.4–0.7 is a soft retry that rewrites the query; repeated failures hit the 3-retry cap.",
  S2, [282, 283, 284, 285, 286, 287, 288], "score < 0.4",
  ["score ≥ 0.4", "score < 0.4"]),
]

# ---------------- S3 correctness (Q039..Q058) ----------------
S3 = "S3"
NEW += [
R("S3-Q039", "cite",
  "What does the step-7 input-guardrail layer run to stop prompt injection?",
  "Input guardrails run detect_injection() and reject with 'Potential prompt injection' before the query reaches the RAG pipeline.",
  S3, [125, 126, 127], "detect_injection",
  ["detect_injection", "Potential prompt injection"]),
R("S3-Q040", "cite",
  "Which four checks sit in the step-7 input-guardrails box?",
  "Prompt injection detection, off-topic filtering, rate limiting, and input length validation.",
  S3, [33, 34, 35, 36], "Input length validation",
  ["Prompt injection detection", "Off-topic filtering", "Rate limiting", "Input length validation"]),
R("S3-Q041", "cite",
  "What avg_score and cost_per_query does the V3 candidate record?",
  "V3 records avg_score 0.87 at cost_per_query 0.003, versus production's 0.82 at 0.002.",
  S3, [229], "v3_metrics",
  ["0.87", "0.003", "0.82", "0.002"]),
R("S3-Q042", "cite",
  "What was the documented A/B trade-off for V3?",
  "The decision line reads: 'V3 is 6% better but 50% more expensive.'",
  S3, [231], "6% better but 50% more expensive",
  ["6% better", "50% more expensive"]),
R("S3-Q043", "cite",
  "Which hosting option suits prototypes and costs nothing?",
  "Streamlit Cloud — Low complexity, Free, best for prototypes.",
  S3, [316], "Streamlit Cloud",
  ["Streamlit Cloud", "Free", "Prototypes"]),
R("S3-Q044", "cite",
  "Can a shadow candidate prompt ship before live evidence promotes it?",
  "No — shadow candidates (e.g. RAG_ANSWER_V3_shadow) never ship until live evidence promotes them; registration is staging until evidence decides.",
  S3, [282], "never ships until live evidence promotes it",
  ["never ships until live evidence promotes it", "staging"]),
R("S3-Q045", "cite",
  "Under which PEFT technique does step 8 introduce QLoRA?",
  "QLoRA sits under PEFT re-parameterization — LoRA A/B/alpha/rank, INT8 → NF4 quantization, with double quantization and paged optimizers.",
  S3, [429, 430], "QLoRA",
  ["re-parameterization", "QLoRA", "double quantization"]),
R("S3-Q046", "cite",
  "How does the step-8 roadmap continue after DPO alignment?",
  "SFT (LoRA/QLoRA) → DPO alignment → Guardrails → Red team → Patch → loop.",
  S3, [439], "DPO alignment",
  ["DPO alignment", "Guardrails", "Red team", "Patch"]),
R("S3-Q047", "cite",
  "Where does step 7 simulate total Groq unavailability?",
  "Exercise 6 under 'Test failure modes — what happens when Groq is down?' — the deployment/guardrails step, not a framework bundle.",
  S3, [330], "Groq is down",
  ["Test failure modes", "Groq is down"]),
R("S3-Q048", "cite",
  "What do step-7 pillars 4–6 cover?",
  "Monitoring (tracking production metrics), cost management (token budgeting and rate limiting), and failure handling (graceful degradation when things break).",
  S3, [18, 19, 20], "Graceful degradation when things break",
  ["Monitoring", "Cost management", "Graceful degradation when things break"]),
R("S3-Q049", "cite",
  "What is the default daily budget in the step-7 CostTracker?",
  "The CostTracker example defaults daily_budget to 5.0 (float).",
  S3, [172, 173], "daily_budget: float = 5.0",
  ["daily_budget"]),
R("S3-Q050", "cite",
  "Can a $5 daily budget afford the V2 upgrade at 2000 queries/day?",
  "Yes — the exam answer works it out: V1 costs $3.60/day, V2 costs $4.20/day, both within the $5 budget.",
  S3, [276], "V1 costs $3.60/day",
  ["V1 costs $3.60/day", "V2 costs $4.20/day", "within budget"]),
R("S3-Q051", "cite",
  "What does the step-7 monitoring dashboard example show for rejected queries?",
  "It breaks rejected queries down by guardrail — the example shows 'Off-topic: 45' as one of the counts.",
  S3, [304], "Off-topic: 45",
  ["Off-topic: 45"]),
R("S3-Q052", "cite",
  "Which step-7 file tracks token budgeting and cost-per-version?",
  "cost_tracker.py — marked NEW for token budgeting + cost-per-version.",
  S3, [95], "cost_tracker.py",
  ["cost_tracker.py", "Token budgeting", "cost-per-version"]),
R("S3-Q053", "misroute",
  "What must be true before a shadow candidate prompt ships?",
  "Only evidence drives promotion — a shadow/A-B candidate ships once its scores beat the incumbent (compare_versions). The tempting target for this answer is the prompt-registry docs, but the shipping rule is step-7 deployment policy.",
  S3, [284], "Evidence drives promotion",
  ["Evidence drives promotion", "compare_versions"]),
R("S3-Q054", "abstain",
  "What is the correct fix for the step-7 latency-spike exam question?",
  "Not recorded: the exam poses the latency-spike case but the corpus records no answer or investigation plan — do not invent one.",
  S3, [351], "Latency spikes from 1s to 5s",
  ["Latency spikes from 1s to 5s"]),
R("S3-Q055", "abstain",
  "What production daily budget does step 7 enforce as policy?",
  "No enforced policy figure is recorded — the corpus shows the CostTracker example default (daily_budget 5.0) in code, not a production configuration.",
  S3, [172, 173], "daily_budget: float = 5.0",
  ["daily_budget"]),
R("S3-Q056", "degrade",
  "What does step 7's failure-handling pillar aim for when components break?",
  "Graceful degradation — the architecture's pillar 6 is 'Failure handling — Graceful degradation when things break'.",
  S3, [18, 19, 20], "Graceful degradation when things break",
  ["Graceful degradation when things break"]),
R("S3-Q057", "degrade",
  "How does step 7 surface degraded conditions in the monitoring dashboard?",
  "The dashboard tracks error rates — the architecture lists Error rates among the tracked production metrics — so degraded days are visible rather than silent.",
  S3, [65], "Error rates",
  ["Error rates"]),
R("S3-Q058", "degrade",
  "What failure mode does the 'Groq is down' exercise stress-test?",
  "A provider outage — the exercise verifies behavior under total Groq failure: graceful degradation and fallback rather than a hard pipeline crash.",
  S3, [330], "Groq is down",
  ["Groq is down", "Test failure modes"]),
]

# ---------------- S4 correctness (Q038..Q058) ----------------
S4 = "S4"
NEW += [
R("S4-Q038", "cite",
  "Why is step 4's configuration centralized instead of scattered?",
  "Every downstream module needs the same three inputs (API keys, model names, storage paths); the config hub centralizes them in config.py — one import instead of ten, env overrides read once at startup, a single ensure_dirs() creates the runtime folders, and accessors (generate_llm(), judge_llm(), embed_model_name()) expose behavior.",
  S4, [24, 25, 26, 27, 28], "ensure_dirs",
  ["ensure_dirs", "generate_llm", "judge_llm"]),
R("S4-Q039", "cite",
  "What happens when code_split receives an unknown language?",
  "The facade forwards text, chunk_size, overlap plus language for code; code_split maps the alias to language-aware separators, falling back to generic recursive for unknown languages.",
  S4, [129, 130, 131], "falling back to generic recursive",
  ["language-aware separators", "generic recursive"]),
R("S4-Q040", "cite",
  "Which three gates keep the Ragas path cost-free in CI?",
  "The judge is built lazily, tests inject a fake evaluator, and the integration marker (-m integration) separates them; testset.py is never imported by the rest of the eval package.",
  S4, [460, 461], "judge built lazily",
  ["judge built lazily", "fake evaluator", "-m integration"]),
R("S4-Q041", "cite",
  "What does Faiss add over the mini-IVF teaching implementation?",
  "Faiss adds SIMD PQ/IVF compression and HNSW over centroids with the same parameters — production-grade math; the deep lesson is separating the teaching implementation from the production slot-in.",
  S4, [319, 320, 321], "SIMD PQ/IVF compression",
  ["SIMD PQ/IVF compression", "HNSW over"]),
R("S4-Q042", "cite",
  "Which wrapper lets Ragas reuse the step-4 judge, and why is it lazy?",
  "LangchainLLMWrapper(judge_llm()), built lazily at measure time so constructing RagasBackend() never touches the network.",
  S4, [405, 406], "LangchainLLMWrapper",
  ["LangchainLLMWrapper", "lazily at measure time"]),
R("S4-Q043", "cite",
  "What does Ragas' answer_relevancy need that the DeepEval variant does not?",
  "Ragas compares the answer and question in embedding space, which needs an embeddings adapter (the guard raises without one); DeepEval's variant is LLM-judged. The fix is an adapter, not deleting the metric.",
  S4, [450, 451], "embedding space",
  ["embedding space", "guard raises"]),
R("S4-Q044", "cite",
  "How wide are the regression gates' tolerances, and why?",
  "About ±0.03 for the judge and ±20% for latency — tolerances must sit above measurement noise so gates don't fire on random variation.",
  S4, [504, 505], "±0.03",
  ["±0.03", "±20% latency"]),
R("S4-Q045", "cite",
  "What does a cross-backend score gap indicate?",
  "Backends can disagree on the same case — both wrap judge_llm() but latency, context-length effects, and generation randomness differ per framework; a cross-backend gap is a finding, not a bug.",
  S4, [444, 445, 446], "They can disagree",
  ["They can disagree", "generation randomness differ per framework"]),
R("S4-Q046", "cite",
  "Which eval library does the deep-dive recommend for thresholding a single pipeline run?",
  "For thresholding one eval run in a pipeline → DeepEval; the reach-for-which rule (Steps 5–7) also maps deep retrieval forensics → Ragas and golden generation → testset.py.",
  S4, [427, 428, 429, 430], "When to reach for which",
  ["Deep retrieval forensics", "testset.py"]),
R("S4-Q047", "cite",
  "What per-stage latency SLOs does the observability pillar set?",
  "SLO_P95_MS=3000 for end-to-end latency and SLO_TTFT_P95_MS=1200 for time-to-first-token — Task 14's stage-split latency + TTFT.",
  S4, [488], "SLO_P95_MS=3000",
  ["SLO_P95_MS=3000", "SLO_TTFT_P95_MS=1200"]),
R("S4-Q048", "cite",
  "How is the embedding dimension handled in step 4?",
  "Observed, not declared: dim() returns None before the first embed and _coerce records it; there is no dimension=1024 constant, and mixed dims or drift raise ValueError.",
  S4, [245, 246, 247], "Observed, not declared",
  ["Observed, not declared", "dimension=1024"]),
R("S4-Q049", "cite",
  "Which safety items are in the step-4 slice, and what defers to step 7?",
  "Minimal PII (eval_ops_pii.py) is in scope; the full suite — scope/leakage/toxicity/injection/red-team — defers to step 7 (#13/#19).",
  S4, [491], "eval_ops_pii.py",
  ["eval_ops_pii.py", "minimal PII"]),
R("S4-Q050", "cite",
  "What does the gap-register review say about judge pinning?",
  "The judge is pinned so drift is signal, not noise — and the gap register is reviewed at each task.",
  S4, [519], "drift is signal not noise",
  ["judge pinned", "drift is signal not noise"]),
R("S4-Q051", "cite",
  "Which pillar owns Groq→Gemini fallback and per-source where-filters?",
  "The cost ladder / efficiency pillar 6 — Groq→Gemini fallback, per-source where filters (cheap routing), rerankers gated by eval, LangSmith tracing planned.",
  S4, [489], "Groq→Gemini fallback",
  ["Groq→Gemini fallback", "per-source `where` filters"]),
R("S4-Q052", "misroute",
  "Where in the corpus are the concrete SLO latency values (3000 ms / 1200 ms) recorded?",
  "In the step-4 deep dive — the BOM row names SLO_P95_MS=3000 and SLO_TTFT_P95_MS=1200. A router keying on 'SLO / observability' could land on the step-9 README (which only lists Task 14 as owner); the concrete values live in the S4 deep dive.",
  S4, [488], "SLO_P95_MS=3000",
  ["SLO_P95_MS=3000", "SLO_TTFT_P95_MS=1200"]),
R("S4-Q053", "abstain",
  "What is the projected monthly cost of step 4's inference plane?",
  "Not recorded: the cost-ladder pillar names levers (where-filters, fallback, rerankers) and lists cost projection as Task-14 scope, but no projected dollar amount appears in the corpus.",
  S4, [489], "Cost ladder",
  ["Cost ladder", "cost projection"]),
R("S4-Q054", "abstain",
  "What is the measured latency variance of step-4 eval runs?",
  "Not recorded: ±20% is a designed tolerance on the regression harness, not a measurement of run-to-run variance; no measured variance appears in the corpus.",
  S4, [504, 505], "±20% latency",
  ["±20% latency"]),
R("S4-Q055", "degrade",
  "A 400 or auth error hits the generate path. Should the pipeline fall through to Gemini?",
  "No — the fallback is deliberately narrow: only rate-limit errors trigger retry-once-then-fallback; a 400 (malformed prompt) or auth failure won't succeed elsewhere, and falling through masks real bugs, so those propagate.",
  S4, [40, 41], "masks real bugs",
  ["those propagate", "masks real bugs"]),
R("S4-Q056", "degrade",
  "What happens if the judge endpoint fails when the Ragas backend is first measured?",
  "The network is touched at measure time when LangchainLLMWrapper is built lazily; a failing judge surfaces as an error at that call — constructing the backend alone never fails over the network.",
  S4, [405, 406], "LangchainLLMWrapper",
  ["LangchainLLMWrapper", "lazily at measure time"]),
R("S4-Q057", "cite",
  "What does the step-4 BOM say about LangSmith tracing?",
  "LangSmith tracing is 'planned' in the cost-ladder row (pillar 6) — listed with deferrals #8/#9, not implemented in step 4.",
  S4, [489], "LangSmith tracing planned",
  ["LangSmith tracing planned"]),
R("S4-Q058", "cite",
  "How does the regression harness report comparisons?",
  "run_suite produces a snapshot; metric_registry carries direction/kind/tolerance; compare returns PASS(0)/FAIL(1)/REVIEW(2) — the harness is in step 4, CI automation deferred (#14).",
  S4, [487], "run_suite",
  ["run_suite", "metric_registry", "PASS(0)/FAIL(1)/REVIEW(2)"]),
]

# ---------------- S5 correctness (Q037..Q056) ----------------
S5 = "S5"
NEW += [
R("S5-Q037", "cite",
  "Which file sets the default eval backend, and to what value?",
  "eval/contracts/registry.py — get_backend('deepeval' | 'ragas') with DEFAULT_BACKEND = 'deepeval'.",
  S5, [106, 107], "DEFAULT_BACKEND",
  ["get_backend", "DEFAULT_BACKEND"]),
R("S5-Q038", "cite",
  "How does the corpus track the router-misroute deferral?",
  "The non-goals list registers router misroute detection as a tracked deferral, pinned to GAP_REGISTER.md #24 for the query-processing eval; embedding-model version drift (#25) sits beside it.",
  S5, [56], "router misroute detection",
  ["router misroute detection", "embedding-model version drift"]),
R("S5-Q039", "cite",
  "Where do the abstention gate and PII-minimal land in the step-9 module map?",
  "Mod 5 'Guardrails' (pillar 8) — abstention gate + PII-minimal; Mod 7 demo surfaces the abstention/degraded/conflict states.",
  S5, [482], "abstention gate",
  ["Guardrails", "abstention gate"]),
R("S5-Q040", "cite",
  "What does the ux/product interface spec define, and what does it exclude in step 4?",
  "Chat-log schema, batch citations after streamed text, and abstention/degraded/conflict states; no feedback capture in Step 4.",
  S5, [523], "no feedback capture",
  ["Chat-log schema", "no feedback capture"]),
R("S5-Q041", "cite",
  "Which items are tracked as deferred non-goals in the step-4 README?",
  "Safety suite (scope/leakage/toxicity) + injection defense, prompt optimization, LLM fine-tuning/DPO, CI/CD automation, observability tooling (LangSmith), semantic caching, data-freshness/re-indexing, human-feedback loop, access control/multi-tenancy — plus router misroute detection, embedding-model version drift, streaming-citation integrity, and eval-library version pinning.",
  S5, [53, 54, 55, 56, 57], "Non-goals",
  ["prompt optimization", "CI/CD automation", "semantic caching", "human-feedback loop"]),
R("S5-Q042", "cite",
  "What constraint does the step-9 free stack place on the GitHub Actions gate?",
  "The free stack specifies a GitHub Actions offline-only gate.",
  S5, [491], "offline-only",
  ["offline-only"]),
R("S5-Q043", "cite",
  "What strategy order does the step-4 router waterfall use?",
  "Cheap strategies first — rules, then embedding similarity, elevating to the LLM classifier as needed.",
  S5, [156], "Cheap strategies first",
  ["Cheap strategies first", "elevate to LLM classifier"]),
R("S5-Q044", "cite",
  "How does the step-4 prompt registry key prompts per source?",
  "By the composite prompt_id + source_type + version — each source gets a tuned prompt via the shared PromptRegistry with a generic fallback.",
  S5, [153], "prompt_id + source_type + version",
  ["prompt_id + source_type + version", "generic fallback"]),
R("S5-Q045", "cite",
  "Which four source labels do the router tiers decide over?",
  "text / web / pdf / db — the source tags the router's Rules/embedding/LLM tiers decide over.",
  S5, [69, 70], "Rules/embedding/LLM",
  ["Rules/embedding/LLM", "text / web / pdf / db"]),
R("S5-Q046", "cite",
  "How does the step-4 README describe the component-eval backend seam?",
  "As the eval plane — backed by a dual DeepEval+Ragas seam with component evals; the data plane and eval plane are implemented, the inference plane is the current build phase.",
  S5, [16], "eval plane",
  ["eval plane", "DeepEval+Ragas seam"]),
R("S5-Q047", "cite",
  "Which primary→fallback generation rule do the step-9 docs record?",
  "Groq free tier primary → Gemini fallback.",
  S5, [488], "Groq free tier primary → Gemini fallback",
  ["Groq free tier primary → Gemini fallback"]),
R("S5-Q048", "cite",
  "What does the abstention gate return when confidence falls below the gate?",
  "A refusal_string when confidence is below the gate (Task 10).",
  S5, [86], "refusal_string if confidence below gate",
  ["refusal_string"]),
R("S5-Q049", "cite",
  "What does the security role row list as the step-4 safety slice?",
  "PII minimal (Task 14), abstention gate (Task 10), per-source circuit breaker (Task 11), and citation allowlist (Task 10); step-7 items (#19/#22/#23) stay registered OUT.",
  S5, [385], "per-source circuit breaker",
  ["PII minimal (Task 14)", "per-source circuit breaker (Task 11)", "citation allowlist (Task 10)"]),
R("S5-Q050", "cite",
  "What does the SRE role record as step-4 metrics-to-compute?",
  "Latency (TTFT, P95/P99), derived cost, and reliability per Task 14, plus an early-error diagnostics side-channel and per-source health hooks; alerting is Step 7.",
  S5, [386], "early-error diagnostics",
  ["TTFT, P95/P99", "early-error diagnostics", "alerting is Step 7"]),
R("S5-Q051", "misroute",
  "Why is CI automation listed as a deferred item in step 4?",
  "The lifecycle pillar row says registry rollback works now but CI automation defers to Step 7. A router keying on 'CI/gates' could wrongly land on the regression-gates row — the deferral statement is the lifecycle row.",
  S5, [138], "automation* deferred to Step 7",
  ["automation* deferred to Step 7"]),
R("S5-Q052", "abstain",
  "What feedback-capture mechanism does step 4 provide for chat responses?",
  "None — the interface spec explicitly records 'no feedback capture' in Step 4; do not invent a rating or feedback loop.",
  S5, [523], "no feedback capture",
  ["no feedback capture"]),
R("S5-Q053", "abstain",
  "Which alert thresholds does step 4 define for P95 latency?",
  "None recorded: step 4 computes metrics (TTFT, P95/P99) but alerting is explicitly Step 7 — alert thresholds are not in the corpus.",
  S5, [386], "alerting is Step 7",
  ["alerting is Step 7"]),
R("S5-Q054", "degrade",
  "A single source keeps failing. Which step-4 mechanism contains the damage?",
  "The per-source circuit breaker (Task 11) isolates the failing source — the security role row lists it as part of the step-4 slice.",
  S5, [385], "per-source circuit breaker",
  ["per-source circuit breaker (Task 11)"]),
R("S5-Q055", "degrade",
  "When the embedding-sim tier is unavailable, which router tiers take over?",
  "The router is a rules / embedding-sim / LLM waterfall with cheap strategies first; with embedding-sim unavailable it falls back to the cheaper rules tier or elevates to the LLM classifier as needed.",
  S5, [156], "Cheap strategies first",
  ["Cheap strategies first", "elevate to LLM classifier"]),
R("S5-Q056", "degrade",
  "What does the step-9 model line do when the primary generation provider is unavailable?",
  "Falls back to Gemini — 'Groq free tier primary → Gemini fallback' is the recorded generation rule.",
  S5, [488], "Groq free tier primary → Gemini fallback",
  ["Gemini fallback"]),
]

# ---------------- MS correctness (Q014..Q018) ----------------
NEW += [
R("MS-Q014", "conflict",
  "In production, which model scores the eval metrics across the step series?",
  "Both, and they must not be merged: the step-2 suite's judge is openai/gpt-oss-120b (Groq free tier, ~8000 tokens/min), while the step-4 judge is a single fixed Qwen/Qwen2.5-7B-Instruct-AWQ via LLM_BASE_URL.",
  "S1+S4", [1208], "openai/gpt-oss-120b",
  ["openai/gpt-oss-120b", "Qwen/Qwen2.5-7B-Instruct-AWQ"], "S1"),
R("MS-Q015", "multi-source",
  "Which rules govern prompt versioning across the series?",
  "The early registry keeps a forward-only DRAFT → TESTING → APPROVED → RETIRED lifecycle; the graph era adds per-node eval gates recording Evidence, approved versions stay immutable, and status stays data (S2). Both bundles contribute the rule.",
  "S1+S2", [411], "DRAFT → TESTING",
  ["DRAFT → TESTING → APPROVED → RETIRED", "Approved versions immutable"], "S1"),
R("MS-Q016", "conflict",
  "What chunk size does the shared pipeline use?",
  "It depends on the step and strategy: step 1 documents fixed-size chunking at 512 tokens, while step 4's chunker is strategy-driven (language-aware separators, generic recursive fallback). A faithful answer attributes the number to the step.",
  "S1+S4", [127, 128], "512 tokens",
  ["512 tokens", "generic recursive"], "S1"),
R("MS-Q017", "conflict",
  "Is the retrieval score a cosine similarity or a distance?",
  "Both, per step: step 1 computes numpy cosine similarity directly, while step 3 recovers Chroma scores as 1−distance via _collection.query. Do not merge — attribute the scoring to the step.",
  "S1+S2", [173], "Pure numpy",
  ["cosine similarity", "1−distance"], "S1"),
R("MS-Q018", "conflict",
  "Is LangSmith tracing in step-4 scope or deferred?",
  "The corpus says both things: the step-4 README lists observability tooling (LangSmith) among deferred non-goals, while the cost-ladder pillar row records 'LangSmith tracing planned' (✓ partial, deferrals #8/#9). A faithful answer surfaces both statements.",
  "S5+S4", [53, 54], "Non-goals",
  ["observability tooling (LangSmith)", "LangSmith tracing planned"], "S5"),
]

# ---------------- cross-file collision asserts ----------------
for other in (str(ROOT / "eval" / "goldens" / "retriever_goldens.json"),
              str(ROOT / "eval" / "goldens" / "query_processing_goldens.json")):
    ext = json.load(open(other))
    ids = {r["id"] for r in ext}; qs = {r["query"] for r in ext}
    for r in NEW:
        assert r["id"] not in ids, f"cross-file id collision {r['id']} vs {other}"
        assert r["query"] not in qs, f"cross-file query collision {r['id']} vs {other}"

# ---------------- write ----------------
rows = []
have = set()
for r in NEW:
    assert r["id"] not in have, f"dup id {r['id']}"
    assert r["query"] not in (x["query"] for x in rows), f"dup query {r['id']}"
    have.add(r["id"]); rows.append(r)

def seq(i): return int(re.search(r"Q(\d+)", i).group(1))
rows.sort(key=lambda r: ((0 if r["id"].startswith("MS")
                          else {"S1":1,"S2":2,"S3":3,"S4":4,"S5":5}[r["id"][:2]]), seq(r["id"])))
json.dump(rows, open(GOLD, "w"), indent=2, ensure_ascii=False)
print("wrote", len(rows), "correctness rows")