#!/usr/bin/env python3
"""Batch 3: complete retriever_goldens.json to 139 rows (S3 26, S4 26, S5 26, MS 4).
Recipe: doc/design/01_authoring_recipe.md — A() byte-exact extractor + T-01 suite.
Idempotent: reloads committed rows; fixed tuples re-run without duplication.
"""
import json, re

from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]  # this file lives at <repo>/tools/goldens/

DATA = str(ROOT / "data" / "docs") + "/"
GOLD = str(ROOT / "eval" / "goldens" / "retriever_goldens.json")
SRC = {
    "S1": "s1_early_steps_bundle.md", "S2": "s2_frameworks_bundle.md",
    "S3": "s3_lifecycle_bundle.md", "S4": "s4_qa_deep_dives.md", "S5": "s5_docs_bundle.md",
}
bund = {k: open(DATA + v, encoding="utf-8").read() for k, v in SRC.items()}
lines = {k: v.splitlines(keepends=True) for k, v in bund.items()}

def A(src, nums, marker):
    txt = "".join(lines[src][i - 1] for i in nums).rstrip("\n")
    assert marker in txt, f"MARKER FAIL {src} {nums}: {marker!r} -> {txt[:80]!r}"
    assert txt in bund[src], f"NOT CONTIGUOUS {src} {nums}"
    return txt

def expect_path(srcs):
    return " + ".join("data/docs/" + SRC[s] for s in srcs)

def R(i, cat, q, ans, src, nums, marker, must, ctxsrc=None):
    cs = ctxsrc or src
    return {
        "id": i, "category": cat, "query": q, "ideal_answer": ans,
        "ideal_context": A(cs, nums, marker),
        "must_contain": must, "source": src, "path": expect_path(src.split("+")),
    }

NEW = []

# ---------------- S3 batch (Q005..Q026) ----------------
S3 = "S3"
NEW += [
R("S3-Q005", "cite",
  "What checks does input-guardrail validation run before a query reaches the RAG pipeline?",
  "InputGuardrails.validate() runs four checks in order: length (rejects queries over 10,000 chars with 'Query too long'), prompt-injection detection (rejects with 'Potential prompt injection'), an off-topic check ('Question not related to loaded documents'), and rate limiting ('Rate limit exceeded'). Only if all pass does it return True.",
  S3, list(range(119, 138)), "Potential prompt injection",
  ["Query too long", "Potential prompt injection", "Question not related to loaded documents", "Rate limit exceeded"]),
R("S3-Q006", "cite",
  "What makes the output guardrails reject an LLM answer?",
  "OutputGuardrails.validate() rejects on three conditions: faithfulness of the answer against context below 0.5 ('Answer not supported by context'), detected toxicity ('Answer contains inappropriate content'), or citations that fail verification against the context ('Invalid citations').",
  S3, list(range(147, 163)), "Answer not supported by context",
  ["Answer not supported by context", "detect_toxicity", "Invalid citations"]),
R("S3-Q007", "cite",
  "What happens when today's LLM spend exceeds the configured daily budget?",
  "CostTracker carries a daily_budget (default $5.0). track() computes the cost for the tokens and model, accumulates it into today_usage, and raises BudgetExceeded (\"Daily budget $5.0 exceeded\") once usage passes the budget.",
  S3, list(range(171, 182)), "daily_budget",
  ["daily_budget", "calculate_cost", "BudgetExceeded"]),
R("S3-Q008", "cite",
  "In shadow testing, which answer does the user actually see?",
  "Shadow testing runs production with the current approved prompt and, in the background (user doesn't see), the new candidate prompt version (V3_shadow). The results are logged, but the user only ever sees the production answer returned by prompt_version=\"current\".",
  S3, list(range(198, 208)), "User only sees production answer",
  ["V3_shadow", "log_shadow_result", "User only sees production answer"]),
R("S3-Q009", "cite",
  "How does the A/B router split traffic between production and the candidate prompt?",
  "ABTestRouter computes user_hash = hash(question) % 100; a hash below 90 routes to 'current' (90% of traffic) and the rest goes to 'V3_candidate' (10% of traffic).",
  S3, list(range(215, 222)), "10% traffic → candidate",
  ["hash(question) % 100", "90% traffic → production", "10% traffic → candidate"]),
R("S3-Q010", "cite",
  "What was the measured outcome of the V3 prompt after a week of A/B testing?",
  "The A/B comparison recorded prod_metrics avg_score 0.82 at $0.002 per query versus v3_metrics avg_score 0.87 at $0.003 per query — 'V3 is 6% better but 50% more expensive', so the decision rule is to promote if quality matters more than cost, keep as candidate if cost is critical.",
  S3, list(range(227, 234)), "6% better but 50% more expensive",
  ["avg_score", "0.82", "0.87", "6% better but 50% more expensive", "Promote if quality matters more than cost"]),
R("S3-Q011", "cite",
  "Why can prompt-registry rollback be a data operation instead of a code redeploy?",
  "Because the mechanism (the shared registry class) is separate from the state: production answers come from registry.get(prompt_id, approved_only=True), so rolling back means flipping status in registry.json — no code redeploy, no binary rollback.",
  S3, [283], "No code redeploy, no binary rollback.",
  ["registry.get(prompt_id, approved_only=True)", "flipping status in", "No code redeploy, no binary rollback."]),
R("S3-Q012", "cite",
  "What did the monitoring dashboard example show for the day's usage and latency?",
  "The dashboard shows 1,234 requests today, average latency 1.2s, error rate 0.3%, token usage 450,000 / 1,000,000 (45%), and cost today $2.30 / $5.00 (46%).",
  S3, list(range(296, 301)), "450,000 / 1,000,000 (45%)",
  ["Requests today: 1,234", "Error rate: 0.3%", "450,000 / 1,000,000 (45%)", "$2.30 / $5.00 (46%)"]),
R("S3-Q013", "cite",
  "Which deployment option does the corpus pair with high complexity and $50+/month?",
  "Kubernetes is listed as High complexity, $50+/mo, best for Enterprise.",
  S3, list(range(314, 320)), "Kubernetes",
  ["Streamlit Cloud", "AWS Lambda", "Kubernetes", "Enterprise"]),
R("S3-Q014", "cite",
  "With a $5 daily budget and 2000 queries/day, can you afford to switch to the better prompt version?",
  "Yes — the worked exam question computes V1 at $3.60/day and V2 at $4.20/day, and concludes both fit within the $5 budget, so the switch is affordable.",
  S3, [276], "$4.20",
  ["$3.60/day", "$4.20/day", "Yes, within budget"]),
R("S3-Q015", "cite",
  "What does the corpus say is the difference between RAG and fine-tuning?",
  "RAG improves what the model reads; fine-tuning improves how the model behaves and what it knows itself. In production you often want both — a tuned generator fed by a retrieval stack.",
  S3, list(range(410, 413)), "Fine-tuning improves",
  ["what the model reads", "model behaves and what it knows itself", "tuned generator"]),
R("S3-Q016", "cite",
  "What are the three QLoRA tricks?",
  "QLoRA's three tricks are 4-bit NF4 quantization, double quantization, and paged optimizers.",
  S3, [448], "paged optimizers",
  ["4-bit NF4", "double quantization", "paged optimizers"]),
R("S3-Q017", "cite",
  "Why does DPO skip the reward model?",
  "RLHF/PPO needs policy/ref/value/reward models and manages the KL vs reward-hacking tradeoff; DPO instead trains directly on preference pairs — no reward model needed.",
  S3, list(range(431, 433)), "no reward model",
  ["KL vs reward hacking", "no reward model, preference pairs"]),
R("S3-Q018", "cite",
  "What are the recorded cost numbers for RAG_ANSWER_V1 in the cost-per-version table?",
  "RAG_ANSWER_V1 records template_tokens 45, avg_input_tokens 500, avg_output_tokens 200, cost_per_query $0.0018 (from (500+45)×$0.000003 + 200×$0.000006), queries_today 450, and total_cost_today $0.81.",
  S3, list(range(243, 251)), "cost_per_query",
  ["template_tokens", "0.0018", "queries_today", "total_cost_today"]),
R("S3-Q019", "cite",
  "In the seven-step learning path, what does Step 4 (Multi-Source + Routing) add?",
  "Step 4 adds multiple document types and builds query routing.",
  S3, list(range(375, 378)), "Add multiple document types",
  ["Multi-Source + Routing", "Add multiple document types", "Build query routing"]),
R("S3-Q020", "cite",
  "How do prompt versions get promoted to production through the shared registry?",
  "Candidates live in the same shared store as staging/draft records (e.g. RAG_ANSWER_V3_shadow) and never ship until live evidence promotes them; evidence drives promotion when shadow/A-B scores beat the incumbent (compare_versions()); approved versions are immutable — V1 stays byte-identical forever.",
  S3, list(range(282, 286)), "Candidates live in the registry",
  ["staging", "Evidence drives promotion", "V1 stays byte-identical forever"]),
R("S3-Q021", "cite",
  "How does the output guardrail verify citations, and what happens on failure?",
  "OutputGuardrails checks 'are citations real?' via verify_citations(answer, context) — protecting against invented page numbers — and returns False with 'Invalid citations' when verification fails.",
  S3, list(range(158, 161)), "Invalid citations",
  ["verify_citations", "Invalid citations"]),
R("S3-Q022", "cite",
  "What guardrail block counts did the monitoring dashboard example record?",
  "The dashboard records 12 prompt-injection blocks, 45 off-topic blocks, and 8 rate-limited requests.",
  S3, list(range(302, 306)), "Prompt injection: 12",
  ["Prompt injection: 12", "Off-topic: 45", "Rate limited: 8"]),
R("S3-Q023", "cite",
  "What is the Step-8 roadmap order?",
  "The roadmap is SFT (LoRA/QLoRA) → DPO alignment → Guardrails → Red team → Patch → loop.",
  S3, [439], "Red team",
  ["SFT (LoRA/QLoRA)", "DPO alignment", "Guardrails", "Red team", "Patch"]),
R("S3-Q024", "cite",
  "Name the catastrophic-forgetting mitigations the step-8 objectives record.",
  "Under 'Stability & forgetting' the objectives list gradient clipping, LR warm-up/decay, and catastrophic-forgetting mitigations: rehearsal, regularization, weight averaging, and freezing.",
  S3, list(range(426, 428)), "weight averaging",
  ["rehearsal", "regularization", "weight averaging", "freezing"]),
R("S3-Q025", "abstain",
  "After going through all seven steps, how many prompt versions does the registry hold?",
  "Not recorded in the corpus. The Step-7 exam poses this as a self-check ('You've gone through 7 steps. How many prompt versions do you have? How do you manage them?') but nowhere states an actual count — the registry's design (candidates as staging/draft, approved immutable) is documented, the number is not. Do not invent one.",
  S3, [353], "How many prompt versions do you have?",
  ["How many prompt versions do you have?"]),
R("S3-Q026", "conflict",
  "What is the cost premium of the better-scoring prompt version in the A/B comparison — 50% or 17%?",
  "The corpus records both numbers because they compare different version pairs. The shadow/A-B block says 'V3 is 6% better but 50% more expensive' than the current version (0.002 → 0.003 per query); the cost-optimization block says V2 is '17% more expensive for 6% quality improvement' over V1 (0.0018 → 0.0021). A faithful answer must name the version pair before quoting a single percentage.",
  S3, list(range(227, 234)), "6% better but 50% more expensive",
  ["6% better but 50% more expensive", "17% more expensive for 6% quality improvement"]),
]

# ---------------- S4 batch (Q002..Q026) ----------------
S4 = "S4"
NEW += [
R("S4-Q002", "cite",
  "Why is generate_llm() memoized?",
  "Constructing the provider (clients, retries, keys) is expensive/stateful — per-request construction would re-init network clients every time. Memoization means it is constructed once per process and reused; tests reset it via singleton-reset fixtures.",
  S4, list(range(32, 35)), "constructed once per",
  ["expensive/stateful", "constructed once per", "singleton-reset fixtures"]),
R("S4-Q003", "degrade",
  "What happens when Groq rate-limits a Step-4 generation request?",
  "The fallback to Gemini is deliberately narrow: rate limits are transient/expected, so the design is retry-once-then-fallback. A 400 (malformed prompt) or auth failure won't succeed elsewhere — falling through masks real bugs, so those propagate. RATE_LIMIT_ERRORS is a tuple because groq.RateLimitError is NOT a subclass of openai.RateLimitError.",
  S4, list(range(38, 43)), "retry-once-then-fallback",
  ["retry-once-then-fallback", "those propagate", "RATE_LIMIT_ERRORS", "groq.RateLimitError"]),
R("S4-Q004", "cite",
  "Why does the judge use one fixed LLM separate from the generator?",
  "Eval scores must be consistent and reproducible. The generate path (Groq→Gemini) can switch models; if the judge followed that chain, a run could be scored by a different judge than the baseline — invalidating A/B comparisons. A single fixed judge (Qwen/Qwen2.5-7B-Instruct-AWQ) keeps scores comparable across runs.",
  S4, list(range(47, 50)), "invalidating A/B comparisons",
  ["consistent and reproducible", "invalidating A/B comparisons", "Qwen/Qwen2.5-7B-Instruct-AWQ"]),
R("S4-Q005", "cite",
  "Why is DeepEvalJudge built on DeepEvalBaseLLM, and what does generate() return?",
  "DeepEvalBaseLLM is the hook DeepEval uses to call our model for LLM-as-judge metrics. Returning (payload, latency_seconds) is the contract the 3-level suite needs — payload is the raw JSON to log, latency feeds regression (Task 18). Single-invoke design does one JSON-mode call and salvages {\"output\": text} on malformed output instead of retrying the judge.",
  S4, list(range(54, 58)), "latency feeds regression",
  ["DeepEvalBaseLLM", "payload is the raw JSON to", "latency feeds regression", "JSON-mode call"]),
R("S4-Q006", "cite",
  "Why are the test_config.py tests offline, and what is the tradeoff?",
  "No network/keys in CI: provider/persistence are tested with mocks and deterministic inputs. The tradeoff is that real API behavior is not tested — a real-response smoke lives behind env vars. Offline tests catch wiring/caching/contract bugs but can't catch a changed upstream API.",
  S4, list(range(61, 64)), "catch a changed upstream API",
  ["mocks and deterministic inputs", "can't catch a changed upstream API"]),
R("S4-Q007", "cite",
  "Why are secrets env-only while model defaults live in code?",
  "Keys must never be committed. .env holds real values for manual runs; config.py holds model-name defaults (no keys). That keeps 'safe to commit' vs 'never commit' crisp, and .env.example documents the shape.",
  S4, list(range(67, 69)), "model-name",
  ["Keys must never be committed", "model-name", "safe to commit"]),
R("S4-Q008", "cite",
  "Why is recursive_split the default chunking strategy?",
  "It recurses down _RECURSIVE_SEPARATORS = [\"\\n\\n\", \"\\n\", \". \", \" \", \"\"] (paragraphs → sentences → words → chars), respecting natural boundaries so chunks stay readable/coherent for generic content; the other four strategies are for known content types.",
  S4, list(range(91, 94)), "_RECURSIVE_SEPARATORS",
  ["_RECURSIVE_SEPARATORS", "paragraphs", "sentences → words → chars"]),
R("S4-Q009", "cite",
  "How does markdown_split keep context across chunks?",
  "It splits on H1–H3 and injects the header path into every chunk — headers are never standalone, never bleed, so each chunk carries where it came from with no parent lookup. Measured A/B: 87→86 chunks with header injection.",
  S4, list(range(96, 100)), "header path into every chunk",
  ["header path into every chunk", "headers never standalone", "87→86 chunks"]),
R("S4-Q010", "cite",
  "Is deterministic_embedder a chunking strategy?",
  "No — TRAP. It is the offline pseudo-embedding for Layer-1 structural evals: hash-projects each word into a fixed-dim vector and normalizes. SPLITTERS keys exactly five strategies (recursive, character, semantic, markdown, code); strategy='deterministic_embedder' raises ValueError. It is the default embedder the semantic strategy uses when none is injected.",
  S4, list(range(103, 107)), "SPLITTERS",
  ["SPLITTERS", "five strategies", "ValueError"]),
R("S4-Q011", "cite",
  "Why is semantic chunking excluded from chunking_goldens.json despite being offline-deterministic?",
  "Golden bounds written against the stub would mislead once real embedder boundaries differ. Semantic is gated by (a) determinism unit tests now and (b) a Layer-2 cost/quality decision with the real embedder later — goldens are contracts with reality.",
  S4, list(range(110, 113)), "contracts with reality",
  ["would mislead", "Layer-2 cost/quality decision", "contracts with reality"]),
R("S4-Q012", "cite",
  "What can Layer-1 golden bounds tell you, and what can they never tell you?",
  "The golden schema is structural (chunk-count in [min,max], must_contain substring surviving in a single chunk) — it verifies 'didn't break', not ranking. Which strategy retrieves best is a Layer-2 question (Tasks 12/13): hold everything constant, vary strategy, read Contextual Recall vs Precision/Relevancy.",
  S4, list(range(116, 118)), "didn't break",
  ["structural", "didn't break", "Layer-2"]),
R("S4-Q013", "cite",
  "What cost gate does the professor put on semantic chunking?",
  "The cost gate: 'Start with sliding-window and move to semantic only when retrieval quality justifies the cost.' Sliding-window overlap is the cheap go-forward second baseline.",
  S4, list(range(158, 160)), "Start with sliding-window",
  ["Start with sliding-window", "justifies the cost"]),
R("S4-Q014", "cite",
  "What does the professor's classic failure-mode exam question predict when recall goes mediocre after swapping embedders?",
  "Most likely chunk sizes too large, Euclidean distance, or a forgotten query-passage prefix — or the document-parsing/chunking step is losing structure. The embedding model is almost the last knob to turn.",
  S4, list(range(162, 165)), "query-passage prefix",
  ["chunks too large", "Euclidean distance", "query-passage prefix"]),
R("S4-Q015", "cite",
  "What scale boundary does the course material put between Faiss and ChromaDB?",
  "'Faiss scales to billions, ChromaDB to millions.' The corpus then defends picking Chroma + a pedagogical mini-IVF because the corpus is far below the million-vector boundary, with metadata where-filters as the real constraint.",
  S4, [170], "ChromaDB to millions",
  ["Faiss scales to billions", "ChromaDB to millions"]),
R("S4-Q016", "cite",
  "Why is L2-normalization inside the embedder?",
  "Similarity is cosine = dot product of normalized vectors; normalizing in one place means every consumer gets unit vectors for free and can't forget, and the norm is assertable in Layer-1 evals. The zero vector stays all-zero (norm 0 → no NaN).",
  S4, list(range(239, 242)), "norm 0 → no NaN",
  ["dot product of normalized vectors", "unit vectors", "norm 0 → no NaN"]),
R("S4-Q017", "cite",
  "How is the embedding dimension handled — declared or observed?",
  "TRAP: observed, not declared. dim() returns None before the first embed; _coerce records it. There is no dimension=1024 constant; mixed dims or drift raise ValueError. The contract must survive a swapped model (e.g. a future 768-d entry).",
  S4, list(range(245, 248)), "Observed, not declared",
  ["Observed, not declared", "dimension=1024", "Mixed dims or drift raise"]),
R("S4-Q018", "cite",
  "Where does Qwen3Embeddings get its model name, and how would you swap it?",
  "embed_model_name(): EMBED_MODEL env override, else default n24q02m/Qwen3-Embedding-0.6B-ONNX. Change EMBED_MODEL and everything rebuilds via get_embedder(\"qwen3\"); a new provider is a registered class in EMBEDDERS (unknown → ValueError), the same registry pattern as SPLITTERS.",
  S4, list(range(251, 254)), "n24q02m",
  ["n24q02m/Qwen3-Embedding-0.6B-ONNX", "EMBED_MODEL", "get_embedder"]),
R("S4-Q019", "cite",
  "How do Layer-1 evals test a 1024-d neural embedder without downloading it?",
  "Qwen3Embeddings.__init__(backend=...) is the test seam; the real TextEmbedding builds lazily on first use. eval_embeddings.py injects _HashBackend wrapping the 128-d deterministic_embedder, so the structural contract (count/dim/unit-norm/query-parity/factory/config) is verified at zero cost; real-model quality is measured in Task 12 (Layer-2).",
  S4, list(range(258, 261)), "lazily on first use",
  ["test seam", "lazily on first use", "128-d"]),
R("S4-Q020", "cite",
  "How is HNSW tuned, and what is the trap about the knobs?",
  "IndexConfig.chroma_metadata sets hnsw:space / M / construction_ef / search_ef, applied at get_or_create_collection time — knob changes are config, not code. Trap: metadata is honored only at collection creation, so a persisted collection keeps its original knobs.",
  S4, list(range(281, 284)), "metadata honored only",
  ["IndexConfig.chroma_metadata", "metadata honored only", "persisted collection keeps original knobs"]),
R("S4-Q021", "cite",
  "How does search turn Chroma distances into scores?",
  "similarity = float(1.0 - distance), filtered by 'if similarity < min_score: break' on the ascending-distance-sorted list, returned as {text, metadata, score}. Because the collection is cosine and vectors are normalized, distance = 1 - cosine so similarity is exactly cosine; the break needs distance-ascending order and top_k is clamped to collection.count().",
  S4, list(range(293, 297)), "similarity < min_score",
  ["1.0 - distance", "similarity < min_score", "collection.count()"]),
R("S4-Q022", "cite",
  "Why does query use embed_query while add_documents uses embed_documents?",
  "Task-04 instruction-prefix asymmetry (FastEmbed/Qwen3): documents get the doc prefix via embed(); queries get the task-instruction prefix via query_embed(). Flipping either side pollutes Layer-2 A/B with ~1–5% retrieval-quality noise on every strategy.",
  S4, list(range(300, 303)), "Flipping either side",
  ["instruction-prefix asymmetry", "Flipping either side", "1–5% retrieval-quality noise"]),
R("S4-Q023", "cite",
  "Why write a mini-IVF by hand when Chroma (HNSW) is production, and when does it equal brute force?",
  "It is the build-it-by-hand companion to 'how does the production index work': fit runs k-means++; query probes nprobe nearest centroids and scans only those buckets; at nprobe == nlist it equals brute force. The eval sweep quantifies it (nlist=16: 0.930@1 probe → 1.000@4); Faiss-IVF stays a documented slot-in.",
  S4, list(range(306, 309)), "nprobe == nlist",
  ["k-means++", "nprobe == nlist", "0.930@1 probe → 1.000@4"]),
R("S4-Q024", "cite",
  "Which metric engine wins for which need in the dual-backend decision?",
  "DeepEval wins as the cheap always-on CI gate over golden tests (assert thresholds in pytest); Ragas wins for the deep RAG metric battery (20+, e.g. contextual precision) plus synthetic testset generation for Steps 5–7. Both use the same config-driven judge and produce the same neutral Report.",
  S4, list(range(338, 340)), "assert thresholds in pytest",
  ["assert thresholds in pytest", "Deep RAG metric battery", "testset gen"]),
R("S4-Q025", "cite",
  "Why is Ragas pinned to 0.3.1 with langchain-community==0.3.31?",
  "Ragas 0.3.1 is the last of the legacy API line — it imports langchain_community.chat_models.vertexai, which vanished in 0.4.x, so it stays on langchain-community==0.3.31 (a packaging pin, not a choice). The upgrade path touches only backend_ragas.py.",
  S4, list(range(410, 413)), "0.3.31",
  ["Ragas pinned to 0.3.1", "vanished in 0.4.x", "0.3.31"]),
R("S4-Q026", "cite",
  "What would you make a GATE vs a GUARDRAIL in the regression harness?",
  "A gate must not regress (faithfulness pass-rate — hard fail). A guardrail is a soft target (latency P95 — a drop yields REVIEW). Info metrics are tracked but never drive the verdict.",
  S4, list(range(508, 510)), "hard fail",
  ["must not regress", "faithfulness pass-rate", "latency P95", "REVIEW"]),
]

# ---------------- S5 batch (Q004..Q026) ----------------
S5 = "S5"
NEW += [
R("S5-Q004", "cite",
  "Which evaluator backend is the default in the eval registry?",
  "The registry get_backend(\"deepeval\" | \"ragas\") lives in eval/contracts/registry.py with DEFAULT_BACKEND = \"deepeval\".",
  S5, list(range(106, 108)), "DEFAULT_BACKEND",
  ["get_backend", "DEFAULT_BACKEND"]),
R("S5-Q005", "cite",
  "Why does version pinning matter for the two eval engines?",
  "DeepEval is pinned (==2.9.3) and Ragas is floored (>=0.3.1, lockfile-resolved to 0.3.1) precisely because an upstream metric-math change would otherwise look identical to a real regression in the harness (Task 18) — tracked as GAP_REGISTER.md §D row #27.",
  S5, list(range(108, 111)), "metric-math change",
  ["==2.9.3", ">=0.3.1", "metric-math change", "row #27"]),
R("S5-Q006", "cite",
  "What is the Ragas name for the metric our schema calls context_precision?",
  "Ragas 0.3.x spells it ContextPrecision, while DeepEval spells it ContextualPrecisionMetric — same math, different casing; both mean 'relevant chunks ranked first'.",
  S5, [119], "ContextPrecision",
  ["context_precision", "ContextualPrecisionMetric", "ContextPrecision"]),
R("S5-Q007", "cite",
  "What does run_backends return, and what does the seam's protocol require?",
  "run_backends(samples, metric_specs, backends=[...]) runs the same cases through one or more engines and returns {backend_name: Report}. A MetricBackend protocol must expose measure(samples, metric_specs) → Report and validate(metric_specs).",
  S5, list(range(104, 106)), "{backend_name: Report}",
  ["run_backends", "backend_name"]),
R("S5-Q008", "cite",
  "What happens if EMBED_MODEL changes after the vector index is built?",
  "The corpus warns that changing EMBED_MODEL after the index is built requires a full re-embed — see GAP_REGISTER.md #25 for the drift playbook.",
  S5, [207], "full re-embed",
  ["EMBED_MODEL", "full re-embed", "#25"]),
R("S5-Q009", "cite",
  "What routing ladder does Step 4 use, and what embedding-similarity threshold is cited?",
  "Routing is a rules / embedding-sim / LLM waterfall — cheap strategies first, elevate to an LLM classifier as needed — with the embedding-sim threshold ~0.45 from class (Task 06).",
  S5, [156], "0.45",
  ["Cheap strategies first", "embedding-sim threshold ~0.45"]),
R("S5-Q010", "cite",
  "Which pending eval module must include a misrouted-source case?",
  "eval_query MUST include a misrouted-source case — see GAP_REGISTER.md #24 (it lands with Task 12, alongside eval_retriever, eval_retriever_fusion, and eval_generator).",
  S5, list(range(276, 278)), "misrouted-source case",
  ["eval_query", "misrouted-source case", "#24"]),
R("S5-Q011", "cite",
  "How many unit tests does the Step-4 core pass, and what runs only with the integration marker?",
  "uv run pytest -q passes 102 unit tests offline; uv run pytest -m integration exercises the real ONNX embedding + Chroma roundtrip.",
  S5, list(range(230, 232)), "102 unit tests",
  ["102 unit tests", "integration", "Chroma roundtrip"]),
R("S5-Q012", "cite",
  "What is Step 9's one-line thesis?",
  "'Boring infra, smart gates.' Step 9 re-reads the entire step1–8 journey through the LLMOps operating layer, making LLMOps the spine of the story, not a chapter bolted on at the end.",
  S5, [431], "Boring infra, smart gates",
  ["Boring infra, smart gates"]),
R("S5-Q013", "cite",
  "Who writes application code in the step9 repo?",
  "The learner writes every line of application code; agents write markdown only (docs, task contracts, interview Q&A, review verdicts, read-only checks). Agents never write code into src/, tests/, jupyter_notebook/, or CI workflows.",
  S5, list(range(506, 509)), "Agents write markdown only",
  ["Agents write markdown only", "The learner writes every line of application code", "never write code into"]),
R("S5-Q014", "cite",
  "What does Module 1 (Data & testset) of Step 9 cover?",
  "Mod 1 is 'Data & testset (goldens)' under pillar 1 — corpus prep + golden questions.",
  S5, [478], "corpus prep + golden questions",
  ["Data & testset", "corpus prep + golden questions"]),
R("S5-Q015", "cite",
  "What CI gate does the Step-9 free stack use, and what is the pillar-6 budget?",
  "GitHub Actions runs an offline-only gate; free-tier quotas are the pillar-6 budget — the constraint is the lesson.",
  S5, list(range(490, 492)), "offline-only gate",
  ["GitHub Actions", "offline-only gate", "Free-tier quotas are your pillar-6 budget"]),
R("S5-Q016", "cite",
  "What backs the Step-4 three-level evaluation suite?",
  "The suite is backed by two metric engines (DeepEval + Ragas) and a regression harness — proving it works with a three-level evaluation suite.",
  S5, list(range(7, 9)), "DeepEval + Ragas",
  ["three-level evaluation suite", "DeepEval + Ragas", "regression harness"]),
R("S5-Q017", "cite",
  "What is the notebook-first development path, and when does code promote?",
  "Loaders → chunking → embedding → (search) are explored in jupyter_notebook/ plants before promoting into src/ — plain LangChain cells first, promotion only after the loop is proven.",
  S5, [45], "before promoting to `src/`",
  ["jupyter_notebook", "before promoting to `src/`"]),
R("S5-Q018", "cite",
  "What does hybrid retrieval combine, and in what order?",
  "Hybrid retrieval is dense (cosine) + sparse (BM25) → fuse → rerank, returning top-k with source metadata.",
  S5, [79], "dense (cosine) + sparse (BM25)",
  ["dense (cosine) + sparse (BM25)", "fuse → rerank"]),
R("S5-Q019", "cite",
  "What are the five chunking strategies behind the Chunker facade?",
  "The five strategies are character, recursive, markdown, semantic, and code, behind one Chunker facade (implemented + tested).",
  S5, [33], "5 strategies",
  ["`character`, `recursive`, `markdown`, `semantic`, `code`", "Chunker` facade"]),
R("S5-Q020", "cite",
  "What is the 'code delta' claim of Step 9?",
  "The code delta is tiny: config-as-package, judge wiring, the CI gate, the demo UI. Everything deep (mini-IVF, dual-backend eval, regression harness) stays a cross-reference to step4 — you re-learn the patterns, you do not duplicate the machinery.",
  S5, list(range(447, 449)), "config-as-package",
  ["code delta is tiny", "config-as-package", "judge wiring"]),
R("S5-Q021", "cite",
  "What decides which source(s) a question hits in the Step-4 router, and what are the source tags?",
  "The router uses Rules/embedding/LLM to decide which source(s) to query; source tags are text / web / pdf / db.",
  S5, list(range(69, 71)), "Rules/embedding/LLM",
  ["Rules/embedding/LLM", "source tags: text / web / pdf / db"]),
R("S5-Q022", "cite",
  "What corpus do the step9 data-role notes say backs this repo?",
  "The corpus is self-authored step-series doc bundles (S1–S5, D14) with {text, metadata} schema and source tags; #25 embedding-drift playbook is mapped.",
  S5, [522], "S1–S5",
  ["self-authored step-series doc bundles", "S1–S5"]),
R("S5-Q023", "cite",
  "What judge setup does the Step-9 free stack specify?",
  "Judge via an OpenAI-compatible endpoint (default Qwen/Qwen2.5-7B-Instruct-AWQ), with a local Ollama candidate — to be verified in NB-000, not assumed.",
  S5, list(range(489, 491)), "Ollama",
  ["Qwen/Qwen2.5-7B-Instruct-AWQ", "Ollama", "verify in NB-000"]),
R("S5-Q024", "cite",
  "Why must source metadata propagate onto every chunk?",
  "Every chunk carries its source — routing, retrieval, generation, and per-source eval all depend on it; without it, citations and per-source tuning break.",
  S5, [154], "Source metadata propagation",
  ["Every chunk carries its source", "per-source eval all depend on it"]),
R("S5-Q025", "cite",
  "What is the rationale for running both DeepEval and Ragas behind one neutral seam?",
  "DeepEval is the pytest/CI gate (threshold, minimal footprint); Ragas adds the deepest retrieval metric battery plus a synthetic-testset generator for Steps 5–7. One neutral seam, both engines, same judge — EvalCase/MetricResult/Report decouple tests from any vendor so the metric framework stays swappable.",
  S5, list(range(150, 152)), "One neutral seam",
  ["One neutral seam, both engines, same judge", "EvalCase", "swappable"]),
R("S5-Q026", "cite",
  "Which Step-4 planes are implemented today, and which is the current build phase?",
  "The data plane (ingestion, chunking, embeddings, vector store) and the eval plane (dual DeepEval+Ragas seam, component evals) are implemented and tested (102 unit + integration tests, real-mode smoke). The inference plane (routing → hybrid retrieval → rerank → cited generation → pipeline → CLI/UI) is the current build phase, scaffolded per doc/task/.",
  S5, list(range(15, 20)), "current build phase",
  ["data plane", "eval plane", "inference", "current build phase"]),
]

# ---------------- MS rows ----------------
NEW += [
R("MS-Q003", "conflict",
  "What embedding dimension does the shared pipeline use — 1024-dim as Step 3 records, or the dimension the embedder observes at runtime?",
  "The corpus records two different truths. The Step-3 rebuild states 'Same embedding as Step 2 (qwen3-embed, 1024-dim)' — a nominal 1024-dim claim. But the Step-4 deep-dive says dimension is observed, not declared: dim() returns None before the first embed, _coerce records it, there is no dimension=1024 constant, and the Layer-1 stub wraps a 128-d deterministic embedder. A faithful answer surfaces the discrepancy (and the #25 drift risk) instead of picking one number.",
  "S2+S4", list(range(245, 248)), "Observed, not declared",
  ["qwen3-embed, 1024-dim", "Observed, not declared", "dimension=1024", "128-d"], "S4"),
R("MS-Q004", "degrade",
  "Groq returns a 500 error mid-request. Does the pipeline fail gracefully?",
  "The corpus grounds both a goal and a rule. The step-7 objective states failure handling means graceful degradation when things break, and its exam asks exactly this question. The step-4 fallback rule is deliberately narrow: only rate-limit errors get retry-once-then-fallback to Gemini — falling through on a permanent error (like a 500-class failure that won't succeed elsewhere) masks real bugs, so those propagate and are surfaced (error-rate monitoring) rather than silently swallowed.",
  "S3+S4", [352], "Does your pipeline fail gracefully?",
  ["Graceful degradation when things break", "Does your pipeline fail gracefully?", "retry-once-then-fallback", "those propagate"], "S3"),
]

# ---------------- idempotent append + sort ----------------
rows = json.load(open(GOLD))
by_id = {r["id"]: r for r in rows}
for r in NEW:
    by_id[r["id"]] = r  # insert or update (self-correcting idempotency)
rows = list(by_id.values())
have = {r["id"] for r in rows}
missing = [r["id"] for r in NEW if r["id"] not in have]

def seq(i): return int(re.search(r"Q(\d+)", i).group(1))
rows.sort(key=lambda r: ((0 if r["id"].startswith("MS")
                          else {"S1":1,"S2":2,"S3":3,"S4":4,"S5":5}[r["id"][:2]]), seq(r["id"])))
json.dump(rows, open(GOLD, "w"), indent=2, ensure_ascii=False)
print("upserted", len(NEW), "-> file now", len(rows), "rows (unique ids:", len({r['id'] for r in rows}), ")")